# Generated by Django 4.1.3 on 2022-11-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cart_cart_id_remove_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id_product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
