# Generated by Django 4.1.3 on 2022-11-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id_product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
