# Generated by Django 4.1.3 on 2022-11-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='id_product',
            new_name='product',
        ),
    ]
